# Generated by Django 5.2.15 on 2026-07-04 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('inventory_number', models.CharField(max_length=100, unique=True, verbose_name='Інвентарний номер')),
                ('brand', models.CharField(blank=True, max_length=255, verbose_name='Марка / виробник')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Розташування')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Довжина')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Висота')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Обладнання',
                'verbose_name_plural': 'Обладнання',
                'ordering': ['name', 'inventory_number'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Тип ТО',
                'verbose_name_plural': 'Типи ТО',
                'ordering': ['code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('unit', models.CharField(max_length=50, verbose_name='Одиниця виміру')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Запчастина',
                'verbose_name_plural': 'Запчастини',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('full_name', models.CharField(max_length=255, verbose_name='ПІБ')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Посада')),
            ],
            options={
                'verbose_name': 'Особа',
                'verbose_name_plural': 'Особи',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='MachineSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_maintenance_description', models.TextField(blank=True, verbose_name='Опис щозмінного обслуговування')),
                ('to1_description', models.TextField(blank=True, verbose_name='Опис ТО-1')),
                ('to2_description', models.TextField(blank=True, verbose_name='Опис ТО-2')),
                ('to3_description', models.TextField(blank=True, verbose_name='Опис ТО-3')),
                ('machine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specification', to='maintenance.machine', verbose_name='Обладнання')),
            ],
            options={
                'verbose_name': 'Специфікація обладнання',
                'verbose_name_plural': 'Специфікації обладнання',
                'ordering': ['machine__name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_date', models.DateField(verbose_name='Запланована дата')),
                ('status', models.CharField(choices=[('planned', 'Заплановано'), ('done', 'Виконано'), ('overdue', 'Прострочено'), ('cancelled', 'Скасовано')], default='planned', max_length=20, verbose_name='Статус')),
                ('note', models.TextField(blank=True, verbose_name='Примітка')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_plans', to='maintenance.machine', verbose_name='Обладнання')),
                ('maintenance_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_plans', to='maintenance.maintenancetype', verbose_name='Тип ТО')),
            ],
            options={
                'verbose_name': 'План ТО',
                'verbose_name_plural': 'Плани ТО',
                'ordering': ['planned_date', 'machine__name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_date', models.DateField(verbose_name='Дата виконання')),
                ('work_description', models.TextField(verbose_name='Опис виконаних робіт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='maintenance.machine', verbose_name='Обладнання')),
                ('related_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_logs', to='maintenance.maintenanceplan', verbose_name="Пов'язаний план")),
                ('maintenance_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_logs', to='maintenance.maintenancetype', verbose_name='Тип ТО')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executed_maintenance_logs', to='maintenance.person', verbose_name='Виконавець')),
                ('responsible_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_maintenance_logs', to='maintenance.person', verbose_name='Відповідальна особа')),
            ],
            options={
                'verbose_name': 'Журнал ТО',
                'verbose_name_plural': 'Журнал ТО',
                'ordering': ['-performed_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MachinePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Кількість')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_parts', to='maintenance.machine', verbose_name='Обладнання')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_parts', to='maintenance.part', verbose_name='Запчастина')),
            ],
            options={
                'verbose_name': 'Запчастина обладнання',
                'verbose_name_plural': 'Запчастини обладнання',
                'ordering': ['machine__name', 'part__name'],
                'unique_together': {('machine', 'part')},
            },
        ),
    ]
