# Generated by Django 5.2.15 on 2026-07-04 21:46

import django.db.models.deletion
from django.db import migrations, models


def normalize_person_positions(apps, schema_editor):
    Person = apps.get_model('maintenance', 'Person')
    position_mapping = {
        'механік': 'mechanic',
        'слюсар': 'locksmith',
        'слюсар-ремонтник': 'locksmith',
        'головний інженер': 'chief_engineer',
        'начальник підготовчої дільниці': 'preparation_section_head',
        'інше': 'other',
    }

    for person in Person.objects.all():
        normalized = (person.position or '').strip().lower()
        if not normalized:
            continue
        person.position = position_mapping.get(normalized, 'other')
        person.save(update_fields=['position'])


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancelog',
            name='executor',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='executed_maintenance_logs', to='maintenance.person', verbose_name='Виконавець'),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='responsible_person',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_maintenance_logs', to='maintenance.person', verbose_name='Відповідальна особа'),
        ),
        migrations.AlterField(
            model_name='person',
            name='position',
            field=models.CharField(blank=True, choices=[('chief_engineer', 'головний інженер'), ('preparation_section_head', 'начальник підготовчої дільниці'), ('mechanic', 'механік'), ('locksmith', 'слюсар'), ('other', 'інше')], max_length=50, verbose_name='Посада'),
        ),
        migrations.RunPython(normalize_person_positions, migrations.RunPython.noop),
    ]
