# Generated by Django 5.2.15 on 2026-07-07

from django.db import migrations


def seed_maintenance_types(apps, schema_editor):
    MaintenanceType = apps.get_model("maintenance", "MaintenanceType")
    default_types = [
        ("0", "ЩЗТО", "Щозмінне технічне обслуговування."),
        ("ТО-1", "Технічне обслуговування 1", "Планове технічне обслуговування першого рівня."),
        ("ТО-2", "Технічне обслуговування 2", "Планове технічне обслуговування другого рівня."),
        ("ТО-3", "Технічне обслуговування 3", "Планове технічне обслуговування третього рівня."),
        ("КР", "Капітальний ремонт", "Капітальний ремонт обладнання."),
        ("СР", "Середній ремонт", "Середній ремонт обладнання."),
        ("ПР", "Поточний ремонт", "Поточний ремонт обладнання."),
    ]

    for code, name, description in default_types:
        MaintenanceType.objects.update_or_create(
            code=code,
            defaults={"name": name, "description": description},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0002_alter_maintenancelog_executor_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_maintenance_types, migrations.RunPython.noop),
    ]
