# Generated by Django 5.2.15 on 2026-07-07

from django.db import migrations


ALLOWED_MAINTENANCE_TYPES = [
    ("ТО-1", "Технічне обслуговування 1", "Планове технічне обслуговування першого рівня."),
    ("ТО-2", "Технічне обслуговування 2", "Планове технічне обслуговування другого рівня."),
    ("ТО-3", "Технічне обслуговування 3", "Планове технічне обслуговування третього рівня."),
    ("КР", "Капітальний ремонт", "Капітальний ремонт обладнання."),
    ("СР", "Середній ремонт", "Середній ремонт обладнання."),
    ("ПР", "Поточний ремонт", "Поточний ремонт обладнання."),
]


def limit_maintenance_types(apps, schema_editor):
    MaintenanceType = apps.get_model("maintenance", "MaintenanceType")
    allowed_codes = {code for code, _, _ in ALLOWED_MAINTENANCE_TYPES}

    for code, name, description in ALLOWED_MAINTENANCE_TYPES:
        MaintenanceType.objects.update_or_create(
            code=code,
            defaults={"name": name, "description": description},
        )

    for maintenance_type in MaintenanceType.objects.exclude(code__in=allowed_codes):
        has_plans = maintenance_type.maintenance_plans.exists()
        has_logs = maintenance_type.maintenance_logs.exists()
        if not has_plans and not has_logs:
            maintenance_type.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0003_seed_maintenance_types"),
    ]

    operations = [
        migrations.RunPython(limit_maintenance_types, migrations.RunPython.noop),
    ]
