# Generated by Django 5.2.15 on 2026-07-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0004_limit_maintenance_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="technological_number",
            field=models.CharField(blank=True, max_length=100, verbose_name="Технологічний номер"),
        ),
    ]
