# Generated by Django 5.2.15 on 2026-07-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0005_machine_technological_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="inventory_number",
            field=models.CharField(blank=True, max_length=100, verbose_name="Інвентарний номер"),
        ),
    ]
