# Generated by Django 5.2.10 on 2026-08-27 13:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_machine_inventory_number_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceLogPartUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Використана кількість')),
                ('maintenance_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_parts', to='maintenance.maintenancelog', verbose_name='Запис про виконані роботи')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_log_usages', to='maintenance.part', verbose_name='Запчастина або матеріал')),
            ],
            options={
                'verbose_name': 'Використана запчастина або матеріал',
                'verbose_name_plural': 'Використані запчастини та матеріали',
                'ordering': ['part__name'],
                'unique_together': {('maintenance_log', 'part')},
            },
        ),
    ]
