# Generated by Django 5.2.10 on 2026-08-28 11:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_maintenancelogpartusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartAnalyticalMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_factor', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Кількість')),
                ('source_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytical_mappings', to='maintenance.part', verbose_name='Фактично використана запчастина')),
                ('target_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analytical_mapping_targets', to='maintenance.part', verbose_name='Аналітична відповідність')),
            ],
            options={
                'verbose_name': 'Аналітична відповідність запчастини',
                'verbose_name_plural': 'Аналітичні відповідності запчастин',
                'ordering': ['source_part__name', 'target_part__name'],
                'unique_together': {('source_part', 'target_part')},
            },
        ),
    ]
